# Generated by Django 3.1.1 on 2020-09-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('date_of_birth', models.DateTimeField()),
                ('password', models.CharField(max_length=300)),
                ('is_agreed_emailing', models.BooleanField(default=False)),
                ('is_agreed_texting', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
