# Generated by Django 3.1.1 on 2020-09-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='FilteringColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtering_color', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'filtering_colors',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('main_image', models.URLField()),
                ('hover_image', models.URLField()),
                ('price', models.IntegerField(default=0)),
                ('discount_rate', models.IntegerField(default=0)),
                ('simple_description', models.CharField(max_length=200)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.color')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'promotions',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail_description', models.TextField()),
                ('feature', models.URLField()),
                ('additional_image', models.URLField()),
                ('image', models.URLField()),
            ],
            options={
                'db_table': 'serieses',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sexes',
            },
        ),
        migrations.CreateModel(
            name='Silouette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('silouette', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'silouettes',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sub_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('minimum_size', models.IntegerField(default=0)),
                ('maximum_size', models.IntegerField(default=0)),
                ('manufacture', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('caution', models.CharField(max_length=200)),
                ('quality_assureance', models.CharField(max_length=100)),
                ('as_center', models.CharField(max_length=100)),
                ('manufacture_date', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'product_informations',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.promotion'),
        ),
        migrations.AddField(
            model_name='product',
            name='serise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.series'),
        ),
        migrations.AddField(
            model_name='product',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.sex'),
        ),
        migrations.AddField(
            model_name='product',
            name='silouette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.silouette'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(to='product.Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategory'),
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium_url', models.URLField()),
                ('medium_type', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.AddField(
            model_name='color',
            name='filtering_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.filteringcolor'),
        ),
    ]
