# Generated by Django 3.1.1 on 2020-09-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200917_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medium',
            name='medium_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='as_center',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='caution',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='country',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='manufacture_date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='manufacturer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='material',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productinformation',
            name='quality_assurance',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='additional_image',
            field=models.URLField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='feature',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='series',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
